### ISSUE TITLE
angular-shepherd

### ISSUE THREAD

**Issue by AMZALE** [shepherd-pro/angular-shepherd#2239]
Hi. According to the official documentation there is stepsContainer property, how can I get it and set this a setting using angular-shepherd?

**Comment by chuckcarpenter** [comment]
@AMZALE I moved the issue to the correct code base to better address. 

In this library's README, you can see that tour level options from the [docs](https://shepherdjs.dev/docs/Tour.html#Tour) can be set on the service.  e.g., 

```
import { Component, AfterViewInit } from '@angular/core';
import { ShepherdService } from 'angular-shepherd';
import { steps as defaultSteps, defaultStepOptions} from '../data';

@Component({
  selector: 'shepherd',
  templateUrl: './shepherd.component.html',
  styleUrls: ['./shepherd.component.css']
})
export class ShepherdComponent implements AfterViewInit {

  constructor(private shepherdService: ShepherdService) { }

  ngAfterViewInit() {
    this.shepherdService.defaultStepOptions = defaultStepOptions;
    this.shepherdService.modal = true;
    this.shepherdService.confirmCancel = false;
    this.shepherdService.stepsContainer = document.getElementById('#container-selector'); // this must be an HTMLElement
    this.shepherdService.addSteps(defaultSteps);
    this.shepherdService.start();
  }
}
```

**Comment by AMZALE** [comment]
@chuckcarpenter which version angular-shepherd do you use ? because this property is not available 
all properties  are available from ShepherdService

    confirmCancel: boolean;
    confirmCancelMessage: string;
    defaultStepOptions: Step.StepOptions;
    errorTitle: any;
    isActive: boolean;
    keyboardNavigation: boolean;
    messageForUser: string;
    modal: boolean;
    requiredElements: any[];
    tourName: any;
    tourObject: Shepherd.Tour;
    exitOnEsc: boolean;

**Comment by chuckcarpenter** [comment]
@AMZALE I see, it could be set on the `tourObject` in the options before starting the tour, or I agree it would need to be added to be set before initialize. Happy to take a PR to add that if you prefer?

**Comment by AMZALE** [comment]
@chuckcarpenter  ok thank, it would be nice
