### ISSUE TITLE
Documentation link is not working

### ISSUE THREAD

**Issue by sardul3** [shepherd-pro/angular-shepherd#2244]
<img width="1470" alt="Screenshot 2024-06-24 at 8 38 29 AM" src="https://github.com/shepherd-pro/angular-shepherd/assets/15206322/7618b215-0500-4469-bbcd-a1db2a7fde6e">

**Comment by JacobRice04** [comment]
I had the same issue, turns out the Shepherd documentation has recently moved. It can now be found here:
https://docs.shepherdpro.com/

**Comment by rami-alloush** [comment]
The link is not working again, and the link on the README is not working as well!

**Comment by RobbieTheWagner** [comment]
@rami-alloush perhaps you would like to fix them? If you found something incorrect in a README, that is always a nice easy PR 😃

**Comment by RobbieTheWagner** [comment]
Just updated them
